[features]
resolution = true
skip-lint = false

[programs.localnet]
underwriting = "11111111111111111111111111111111"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo \"Add Anchor tests here\""
